# provide the name of the study area
study_area_name: "Faxe"

# provide a list of municipality codes for this study area
municipalities:
  # - "0410" # Middelfart
  # - "0420" # Assens
  # - "0430" # Faaborg-Midtfyn
  # - "0440" # Kerteminde
  # - "0450" # Nyborg
  # - "0461" # Odense
  # - "0479" # Svendborg
  # - "0480" # Nordfyns
  # - "0482" # Langeland
  # - "0492" # Ærø
  - "0320" # Faxe
  
### NO CHANGES NEEDED BELOW THIS LINE

# provide projected crs 
proj_crs: "EPSG:25832"

# provide token from dataforsyning
dataforsyning_token: "fc5f46c60194d0833dbc2b219b6d500a"
datafordeler_username: "MAKKFGPILT"
datafordeler_password: "Testing23!"

# provide names of layers to use for evaluation
evaluation_layers:
  - "agriculture"
  - "bad"
  - "culture"
  - "facilities"
  - "nature"
  - "pois"
  - "service"