# provide projected crs 
proj_crs: "EPSG:25832"

# fill out token from dataforsyning
dataforsyning_token: "fc5f46c60194d0833dbc2b219b6d500a"
datafordeler_username: "MAKKFGPILT"
datafordeler_password: "Testing23!"

study_area_name: "vestjylland"

# provide wfs layers to import (as strings)
wfs_list:
  - "land_attraktioner"
  - "land_landskabnatur"
  - "land_anvendelse"
  - "facilit_faciliteter"

